### ISSUE TITLE
Build Feature - Version Increment

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#16]
`release MINOR/MAJOR/PATCH` with build always increased (if it exists).

Could also do `release --inc minor/major/patch`.

- [ ] Templating in `version`

**Comment by bovine3dom** [comment]
For smaller projects I often just use the day's date as a version signifier - could HEMTT support that?

**Comment by synixebrett** [comment]
Once templating is done, you *should* be able to do that

**Comment by jonpas** [comment]
@bovine3dom this is how it would look like with `date` templating, just need to support version templating
```toml
version = "{{date \"%Y\"}}.{{date \"%m\"}}.{{date \"%d\"}}"
```

This request is probably best implement with a `version` utility which can:
- Update versions in specified files
- Increment version and apply it back to project

Idea on version file list configuration (files that contain version that needs updating):
```toml
# Specify files where version needs updating, without source (script_version.hpp)
version_files = [
    "mod.cpp",
    "README.md"
]
```

Ideas on `version` utility usage:
```sh
$ hemtt version # Argument --update -u maybe?
$ hemtt version --increment major
$ hemtt version --inc minor	# Maybe not?
$ hemtt version -i patch
```
- `version` would update all files specified in `version_files` config using `p.version` as source
  - Regex matching
    - `x.y.z` and `x.y.z.w` fits HEMTT version specification very well, could just match on that like we do in ACE3's and CBA's `make.py`
- `version -i` would just update `p.version` and run `version` routine (above)

**Comment by BrettMayson** [comment]
This is now possible with hooks, I don't think a specific command is needed
