### ISSUE TITLE
Forced release builds don't delete folder if it's open on Windows

### ISSUE THREAD

**Issue by bovine3dom** [BrettMayson/HEMTT#191]
**HEMTT Version:** `0.6.0`
**Project:** https://gitlab.com/16AA/LSR/lsr-public/commit/190c9915d4c2327a2c44c44044b9e9b21d09ad12

**Description:**

Scary error if `build --release --force` is run when folder is open in Windows explorer, as HEMTT fails to remove it.

```
olie@OLIE-PC /d/P/M/A/m/3/lsr-public> hemtt build --release --force
  Cleaning old release v0.0.0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 145, kind: Other, message: "The directory is not empty." }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Steps to reproduce:**

In Cygwin:

```
hemtt build --release --force
cd releases/0.0.0/@LSR/addons
explorer .
cd -
hemtt build --release --force # scary error
rm -r releases/ # Windows explorer pops up with an error but the folder is removed
hemtt build --release --force # works fine
```

I think either the error message could be improved or the folder should be removed more forcefully.

**Comment by synixebrett** [comment]
The error message is prettier in restructure, unfortunately I don't think there is a clean way to remove the folder more forcefully in rust currently.

**Comment by Chronophylos** [comment]
I think this issue can be closed. The `--force` flag does not exist anymore and the folder structure has changed as well. No files get deleted when running `hemtt release`.
