### ISSUE TITLE
Disable warnings through configuration file

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#197]
**HEMTT Version:** `0.7.0-0.940758`
**Project:** https://github.com/Theseus-Aegis/Mods (updated `hemtt.toml` for restructure)

**Description:**
HEMTT should allow disabling certain warnings through `hemtt.toml` configuration file. Such as armake2 `unquoted-string` or `redefinition-wo-undef`.

_As previously discussed on Slack._

**Steps to reproduce:**
None

**Additional information:**
None

**HEMTT Output:**
None

**Comment by synixebrett** [comment]
Since HEMTT is using the restructured armake2 we are now just receiving the raw error information. We will need to categorize the errors, both HEMTT errors and armake2 errors.

**Comment by BrettMayson** [comment]
As of right now, there aren't any warnings, just errors.

Closed with the release of 1.0.0. If you feel this still needs attention for 1.0.0, please re-open.
