### ISSUE TITLE
Fail entire build on one PBO fail or continue?

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#20]
Straight up question, what is the better way to do this?

Failing on first PBO fail means you don't wait for the build, especially in CI systems. But you also don't see all the errors.

Continuing and just gracefully handling the error means builds are longer, but you can see all the errors and possibly fix them in one go.

I am currently on the side of continuing, but maybe add a flag to "stop on first error".

**Comment by ptMuta** [comment]
I don't really like the idea of partially successful builds, but I do see the benefit of defaulting to `continue on error` for debugging purposes. 

Maybe have the build task store the build artifacts in a temporary directory and do a dist copy only on full success? Also return with an error code in the end to allow CI builds to fail by default on errors.
