### ISSUE TITLE
hemtt template addon doesn't replace "other" from script_component

### ISSUE THREAD

**Issue by bux** [BrettMayson/HEMTT#235]
**HEMTT Version:** 0.7.3

**Description:**

*functions\script_component.ht.hpp*
`#include "\{{MAINPREFIX}}\{{PREFIX}}\addons\other\script_component.hpp"`

**Steps to reproduce:**

* run "hemtt template addon test"

**Comment by BrettMayson** [comment]
This functionality is not present in the 1.0.0 release.

If you feel this still needs attention for 1.0.0, please re-open.
