### ISSUE TITLE
Optional addons moved to addons/ for testing

### ISSUE THREAD

**Issue by BrettMayson** [BrettMayson/HEMTT#24]
As mention by jonpas in #23 there should be a way to built optional addons into `addons/` for the purpose of testing. Not sure exactly how this should be done since you may want to build optionals without the move happening.

**Comment by jonpas** [comment]
Not just PBOs, for file patching to work with optionals we'll want to move the entire addon folder over.

Still not sure how to best do that to be easy and not cram the build flags.

**Comment by BrettMayson** [comment]
Closing, implemented in 0,10 with the `dev` and `launch` commands
