### ISSUE TITLE
Feature Request: Mission File Configuration

### ISSUE THREAD

**Issue by TMZulu** [BrettMayson/HEMTT#269]
**HEMTT Version:** Stable 0.7.4 Release
**Project:** N/A

**Description:**
As I have been told by @synixebrett, the functionality that I am going to state is not present for HEMTT. This being the functionality for HEMTT to be configured to pack specifically mission files. Now single mission files aren't the point, the functionality I have in mind is the ability to have multiple mission files in one folder and a script framework that is the same for all missions in another folder. Then for HEMTT to copy the scripts over to the mission file/folder (i.e. something.Stratis) and pack it into a pbo. The reasoning behind this functionality is for groups that use the same scripts for all missions but have different object placements on each map. Like a community make a bunch of default Zeus mission templates with different spawn bases and such. 

**Suggested Functionality:**

* HEMTT configuration for packing mission file sets or single mission files
* When packing:
   1. Copy mission files into temp instance
   2. Copy script framework into temp
   3. Pack temp instance into pbo
   4. Clear temp instance
* Potentially add it as a separate configuration to `hemtt.toml`

**Additional information/ Ideas on implementation:**

Potential `hemtt.toml` configuration:

```
config = "missions"
scripts = [
  "./scripts/*"
]
exclude = [
  "mission.Stratis"
]
```
Potential File Structure:

```
├── addons/
    ├── mission.Stratis/
        └── mission.sqm
    └── mission.Altis/
        └── mission.sqm
├── scripts/
    ├── description.ext
    └── init.sqf
└── hemtt.toml
```

**Comment by BrettMayson** [comment]
Out of scope for HEMTT imo, I have a tool that does this already but it is specific to my group's setup. I might make changes to that project then release it.
