### ISSUE TITLE
Please add --verbose mode to stop error suppression

### ISSUE THREAD

**Issue by bovine3dom** [BrettMayson/HEMTT#27]
HEMTT currently suppresses warnings after it feels like it has given you enough of one type.

Sometimes old projects have lots of warnings, and I'd like to get all of them in one go.

**Comment by synixebrett** [comment]
The errors are being suppressed from armake2, ideally armake2 could add a `--no-suppress` or a way to dump all warnings to a file

**Comment by jonpas** [comment]
It's just not implemented in armake2 itself yet.

**Comment by synixebrett** [comment]
Do you know if it is planned?

**Comment by jonpas** [comment]
Flag is there, so I assume so.

**Comment by synixebrett** [comment]
armake2 has a `--verbose` but it currently does nothing that I could see. If this is planned to disable the suppression we can use it.

**Comment by jonpas** [comment]
https://github.com/KoffeinFlummi/armake2/pull/16

**Comment by BrettMayson** [comment]
Closed with the release of 1.0.0. If you feel this still needs attention for 1.0.0, please re-open.
