### ISSUE TITLE
Updater broken on other drives

### ISSUE THREAD

**Issue by TMZulu** [BrettMayson/HEMTT#270]
**HEMTT Version:** 0.7.4 Release
**Project:** N/A

**Description:**

Current update system cannot update hemtt.exe if it is not on the C:\ drive.

**Steps to reproduce:**

- Set up a project on a different drive from C:\
- Use command to update hemtt.exe using `hemtt.exe update`

**Additional information:**

This appears to be a copy issue where whatever is being used cannot go across drives.

**HEMTT Output:**

```
E:\Projects\F7>hemtt.exe update
Checking target-arch... x86_64-pc-windows-msvc
Checking current version... v0.7.3
Checking latest released version... v0.7.4
New release found! v0.7.3 --> v0.7.4
New release is compatible

hemtt.exe release status:
  * Current exe: "E:\\Projects\\F7\\hemtt.exe"
  * New exe release: "hemtt-v0.7.4-x86_64-pc-windows-msvc.zip"
  * New exe download url: "https://api.github.com/repos/synixebrett/HEMTT/releases/assets/17399554"

The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] Y
Downloading...
[00:00:00] [========================================] 8.25MB/8.25MB (0s) Done
Extracting archive... Done
Replacing binary file... error: IoError: The system cannot move the file to a different disk drive. (os error 17)

```

**Comment by synixebrett** [comment]
This is an issue with the library being used for updates. [self_update](https://github.com/jaemk/self_update)
