### ISSUE TITLE
Windows build doesn't print git hash on `--version`

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#277]
**HEMTT Version:** `0.7.4`
**Project:** N/A

**Description:**

- `hemtt.exe --version` -> `HEMTT 0.7.3`
- `./hemtt --version` -> `HEMTT 0.7.3-8df045f`
- _0.7.3 because version was never bumped to 0.7.4 on release._

**Steps to reproduce:**

- Run HEMTT with `--version`

**Additional information:**

/

**HEMTT Output:**

/

**Comment by jonpas** [comment]
Looks like `GIT_HASH` environment variable just isn't set for Windows compilation, ref.: https://github.com/synixebrett/HEMTT/blob/master/src/lib.rs#L40

**Comment by synixebrett** [comment]
Unable to reproduce on Windows, were you using CI builds or locally built?

**Comment by jonpas** [comment]
That one was a CI build. CI doesn't read the hash as per my last comment.

**Comment by synixebrett** [comment]
![image](https://user-images.githubusercontent.com/3946739/78274268-2ff62680-74cd-11ea-80bb-d5949ca3b2db.png)

Tried it with the latest windows builds

Seems there is a different bug, AppVeyor has it twice...

**Comment by jonpas** [comment]
Can reproduce the same way, not the original bug with 0.7.5. Maybe it was fixed in CI at some point (addition of GitHub Actions?), but this was introduced.

**Comment by synixebrett** [comment]
Yeah not sure, nothing has changed in the CI jobs since this issue was created

**Comment by BrettMayson** [comment]
Closed with 1.0.0, outdated issue
