### ISSUE TITLE
Build step template variables missing

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#298]
**HEMTT Version:** `0.8.0-dev` (53bcb953c65523060241cf81f4d3432fc32cacc0)
**Project:** Any

**Description:**

`{{time}}` and `{{source}}` template variables are missing from build steps as documented [here](https://synixebrett.github.io/HEMTT/#/scripts?id=foreach).

`{{target}}` and `{{addon}}` work fine.

**Steps to reproduce:**

Use one of the variables in a script.

**Additional information:**

Probably missed in restructure or documentation is outdated.

**HEMTT Output:**

/

**Comment by BrettMayson** [comment]
There is no longer templating in 1.0
