### ISSUE TITLE
Confusion a bit sketchy getting started

### ISSUE THREAD

**Issue by mwpowellhtx** [BrettMayson/HEMTT#307]
**HEMTT Version:** the latest from releases
**Project:** private repo

**Description:**

I'd like to get started using this. I actually started, if you will, by modeling my project structure after such projects as CBA, ACE, ZEN, and so forth. Seems like a sensible structure once you wrap your mind around it. However, getting started from green field, using `HEMTT init`, I'm not quite sure I follow. I do not know what the options are for template, I have `(CBA)` and that's it. And I end up with one `.hemtt` directory. Also, the structure of this directory does not look like anything I am familiar with in ACE or ZEN, for instance.

**Steps to reproduce:**

Simply, from command line, `HEMTT init`.

**Additional information:**

It would be helpful if we had a bit more of a primer getting started as to what to expect. Short of a CBA primer, if you will. Mostly I need to know what is being auto generated, as it were, copied out of templates, this sort of thing. Is HEMTT used to scaffold in new addon components, for instance? And from what, a blank or template addon? Generally, workflow concerns such as that. No sense spending calories and effort I do not need to, right, if the tooling helps in that area.

**HEMTT Output:**

From a Git bash prompt (Windows 7 x64):

```
$ ./tools/hemtt/windows/x64/hemtt.exe init
Project Name > HEQ
Prefix > z\heq
Author > Michael
Template > (cba)
Template Cloned
```

**Comment by mwpowellhtx** [comment]
I am trying something like `./path/to/hemtt.exe addon vehicles` for instance, to add a `vehicles` add on to my project, right, and I get the following, which is consistent with the `--help`, seems like the options are no longer there as documented, and/or the workflow has changed.

```
$ ./tools/hemtt/windows/x64/hemtt.exe addon vehicles
error: Found argument 'addon' which wasn't expected, or isn't valid in this context
USAGE:
    hemtt.exe [FLAGS] [OPTIONS] [SUBCOMMAND]
For more information try --help
```

**Comment by mwpowellhtx** [comment]
Also, assuming I can stand up addons and such once I get the hang of it, I'm not sure I follow the `$PBOPREFIX$` syntax. Where is `PREFIX` defined? I see `MAINPREFIX`. Is `%%addon%%` replaced by something during the process, I would guess? i.e.

```
{{MAINPREFIX}}\{{PREFIX}}\addons\%%addon%%
```

Cheers, thank you!

**Comment by mwpowellhtx** [comment]
I think what I may be seeing are direct or indirect side effects of the unfinished (?) templating effort. Still, if I am doing something wrong here, any other insights are appreciated. Thank you!

**Comment by Fusselwurm** [comment]
![unknown](https://user-images.githubusercontent.com/52833/81548630-dc091800-937d-11ea-8936-d7a8970ef688.png)

@mwpowellhtx had the same problem, and got told that apparently we're in a period where templating a new project doesnt work, and it's a known problem. see above screenshot for workaround.

**Comment by mwpowellhtx** [comment]
Any ideas when the templating efforts might be completed?

**Comment by BrettMayson** [comment]
Should be cleared up with v0.10
