### ISSUE TITLE
Add optionals, compats, etc, opt out flags

### ISSUE THREAD

**Issue by mwpowellhtx** [BrettMayson/HEMTT#309]
**HEMTT Version:** `0.7.4`+

**Description:**

Is there an "opt out" option for bits such as `--opts` and `--compats`. I did not exhaust my background discovery there. i.e. `--no-opts`, `--no-compats`.

**Additional information:**

Use case, if I've got my eyes on stubbing in some *optionals*, *compats*, etc, but would like to bypass a build just for the moment.

**Comment by BrettMayson** [comment]
Closed with the release of 1.0.0. If you feel this still needs attention for 1.0.0, please re-open.

**Comment by mwpowellhtx** [comment]
Do not have a re-open option. But I think it might be a useful flag.
