### ISSUE TITLE
Improve command descriptions to be more understandable

### ISSUE THREAD

**Issue by CreepPork** [BrettMayson/HEMTT#317]
**HEMTT Version:** `0.7.6` (stable)
**Project:** N/A

**Description:**

I would like to see a broader description of the specifics of each command in the `help` command output. Because looking at some of the commands like `pack` and `build` you have no idea what the difference between them is without looking at the source code.

It basically boils down to this idiom:
```js
class Cat { /* some stuff */ };

// Creates a new cat
const cat = new Cat();
```

That is the feeling I get when looking at some of the commands descriptions.

**Comment by BrettMayson** [comment]
Descriptions in the terminal are a bit more clear in 1.3, and The HEMTT Book will also help with understanding commands
