### ISSUE TITLE
Can't execute 0.7.6 executable on Linux (Ubuntu/Debian)

### ISSUE THREAD

**Issue by CreepPork** [BrettMayson/HEMTT#341]
**HEMTT Version:** `0.7.6` stable
**Project:** N/A

**Description:**

```
creeppork@Debian-Hetzner:~/beacon$ ./hemtt help
-bash: ./hemtt: cannot execute binary file: Exec format error
```

**Steps to reproduce:**

- Download the binary
- `chmod +x hemtt`
- `./hemtt`
- Observe error

**Additional information:**

This only happens with the 0.7.6 binary of GitHub releases. And on Ubuntu and a Debian distro.

**HEMTT Output:**

N/A

**Comment by severgun** [comment]
Because there is no 0.7.6 linux binary. One in release section is for MacOS.

**Comment by Freddo3000** [comment]
Has the Linux version been abandoned?

**Comment by severgun** [comment]
whole project seems dead

**Comment by BrettMayson** [comment]
Work is mainly focused on the experiment branch, the main branch is just focused on essential maintenance.

**Comment by BrettMayson** [comment]
Mac, Windows, and Linux versions can all be taken from the latest build https://github.com/BrettMayson/HEMTT/runs/1788824037
