### ISSUE TITLE
Cleaning not properly done on release build

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#347]
**HEMTT Version:** `0.7.6` (stable or dev + commit hash)
**Project:** https://github.com/Theseus-Aegis/TheseusServices

**Description:**

`--release --force` doesn't properly clear development build PBOs and fails signature checks afterwards.

**Steps to reproduce:**

- Go to https://github.com/Theseus-Aegis/TheseusServices/releases/tag/v1.14.0
- Try `brokenSign` version, observe bisign check verifies successfully but game fails.
- Run `clean` or remove built PBOs manually and rebuild a release build, observe it works. Also observe new build size is different!

**Additional information:**

> 13:15 Brett: The good mod has ODOL models, the bad one has MLOD

It appears already built PBO contents don't get re-binarized. Could be related to building development on Linux and release on Windows. As Linux can't binarize. HEMTT should still properly clear all old stuff though, especially with `--force`.

**HEMTT Output:**

/

**Comment by BrettMayson** [comment]
Closing, fixed with 0,10
