### ISSUE TITLE
Add Toggle for not creating Signs/Keys on Release build

### ISSUE THREAD

**Issue by jokoho48** [BrettMayson/HEMTT#359]
**HEMTT Version:** 3f970a9c1221bba4346279c462ba162c91e7a3e6 (stable or dev + commit hash)

**Description:**
if you work on a server only mod that would break/create issues when loading it on the client it would be useful to have a toggle to not generate signs and keys so server admins don't mistakenly allow client-side loading

**Solution:**
Add a Toggle to the Hemtt.toml for Disabling Signing/Key Creation
doNotSign, doNotGenerateKey?
and if it should be really fancy read/find a file in the PBO to check if that current PBO should be signed

**Comment by BrettMayson** [comment]
Included in 1.2
