### ISSUE TITLE
Hemtt tries to binarize already binarized p3d

### ISSUE THREAD

**Issue by Walthzer** [BrettMayson/HEMTT#411]
**HEMTT Version:** 0.7.6 [dev](https://github.com/BrettMayson/HEMTT/commit/51deaa66b3a376e07442cbd914ef300ad469dadf)
**Project:** [RID](https://github.com/Walthzer/RID)

**Description:**

Hemtt tries to rebinarize p3d's which are already binarized. 
And fails in the process, not creating a pbo and not giving any error messages.

**Steps to reproduce:**

- Run hemtt on a project with binarized p3d's

**HEMTT Output:**
```
HEMTT 0.7.6
Environment: dev

Clean       
Clear          [00:00:00] [##############################] [1|1]
Checks         [00:00:00] [##############################] [1|1]
Prebuild       [00:00:00] [##############################] [1|1]
Build          [00:00:06] [##############################] [1|1]
```

**Comment by BrettMayson** [comment]
This is fixed in HEMTT 1.0
