### ISSUE TITLE
Error in launching

### ISSUE THREAD

**Issue by linkion** [BrettMayson/HEMTT#450]
trying to run hemtt.exe launch and getting the error

`error: Arma 3 not found in Steam`

I do have Arma 3 on a second D:/ drive, could that be it?

**Comment by BrettMayson** [comment]
It should be able to find it on any drive, as long as it is installed via Steam

**Comment by linkion** [comment]
I tried verifying the game files for arma 3, no luck.

I then reinstalled arma, nothing.

When I ran

``` rust
let mut steamdir = SteamDir::locate().unwrap();
let apps: &HashMap<u32, Option<SteamApp>> = steamdir.apps();

let mut w = Vec::new();
writeln!(&mut w, "{:#?}", apps);
```

using the [fully-switch-from-steamy-vdf](https://github.com/LovecraftianHorror/steamlocate-rs/tree/fully-switch-from-steamy-vdf) branch I get no values of `Option<SteamApp>`:
```
...,
440: None,
570: None,
107410: None, <- Arma 3
1009850: None,
...
```
While when I ran with [steamlocate-rs](https://github.com/WilliamVenner/steamlocate-rs) by [WilliamVenner](https://github.com/WilliamVenner)
It does find all values of `Option<SteamApp>` except for Arma 3

Example:
```
440: Some(
        SteamApp {
            appid: 440,
            path: "D:\\SteamLibrary\\steamapps\\common\\Team Fortress 2",
            vdf: Table(
                ...
            ),
            name: Some(
                "Team Fortress 2",
            ),
            last_user: Some(
                ...,
            ),
        },
    ),
```

**Comment by linkion** [comment]
So I narrowed it down and found that some more apps weren't included in the steamlocate,

1. Arma 3
2. Halo: Master Chief Collection
3. Pavlov VR
4. SteamVR
5. Steamworks Common Redistributables

While I can see why 4 and 5 aren't included, 
1,2, & 3 all have in common that they are big from either having a lot of mods or DLCs.

**Comment by BrettMayson** [comment]
I might get a chance to look into this sometime, but I can't replicate so I'm not much help. If you haven't already, I would recommend creating an issue on https://github.com/WilliamVenner/steamlocate-rs/pull/9, but it looks like nothing has moved on that in several months.

**Comment by linkion** [comment]
ok, thanks

**Comment by CosmicHorrorDev** [comment]
@linkion Sorry for the ping, but I'm back to working on WilliamVenner/steamlocate-rs#9

I've fixed some parsing issues where things were too strict if you want to give the most recent commit on that branch another whirl (if you can still reproduce issues). If you have any problems feel free to leave a comment on the PR, so we can get things sorted out. Everything is horribly under-specified and the existing information I can find is scattered around a half a dozen wiki pages and repos, so the more testing things can get the better
