### ISSUE TITLE
Glob issue v0.10 Alpha 13

### ISSUE THREAD

**Issue by TACHarsis** [BrettMayson/HEMTT#454]
### Issue:

Glob pattern in files.include does not work as expected.

### Expectation:

Use of     `"./*.paa"` or `"/*.paa"` in files.include will copy all `.paa` files from project root to output directory.

### Result:

None of them are copied.

### Reproduction steps:

1. have one or more `.paa` files in project root.
2. Add 
```sqf
[files]
include = [
    "./*.paa",
    "/*.paa",
]
```
either together or separately to `project.toml`. 
3. Build with `dev`.
4. See that none of the `.paa` files are copied over.

### Additional Info:

Probably expected, but putting `"*.paa"` will copy all `.paa` files from all subdirectories to the output directory.

**Comment by BrettMayson** [comment]
Fixed in ab6ffdc2bf69f800ef18966a6004884360801881

**Comment by BrettMayson** [comment]
Released in Alpha 14
