### ISSUE TITLE
`asc` on Linux is not executable (v10-a14)

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#456]
HEMTT extracts `asc` binary on Linux to `/tmp/hemtt/.../asc/asc`, but it does not mark it as executable. `chmod +x` during preprocessing confirms it works correctly.

**Comment by BrettMayson** [comment]
Should be fixed in d95e3b5bbf4d61f3e4de0d78b58a5e774396db61, but I don't have access to Linux to test at the moment

**Comment by jonpas** [comment]
Fixed fully in afa9b80e11f2a2dbe8c98dd3ef58ccd9e6f92b38.
