### ISSUE TITLE
Commas in strings errors preprocessor (v10-a14)

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#457]
```sqf
ERROR_3("JNI failed (result: %1, return: %2, error: %3)",_result,_returnCode,_errorCode);
```
Results in `expected 4 got 6`. Removing commas fixes the error.

---

Brett on ACE Discord:
> https://github.com/BrettMayson/HEMTT/blob/main/libs/preprocessor/src/lib.rs#L533 yeah missing a check for being in a string

**Comment by BrettMayson** [comment]
Fixed in d95e3b5bbf4d61f3e4de0d78b58a5e774396db61
