### ISSUE TITLE
Incosistent `prefix` and `name` usage (v10-a14)

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#459]
Old optional folders were named `@{{modname}}_...`,
new ones are just using `@{{prefix}}_...`.

Meanwhile zip name is `{{name}}....zip`.

A bit inconsistent overall with `name` and `prefix` use.

**Comment by BrettMayson** [comment]
I think we should just use all prefix for these, as the names can often not be pretty as filenames. Anyone with objections to that?

**Comment by jonpas** [comment]
I am fine with that, as long as we can change it at some point in the future to keep naming the same for existing project releases.

**Comment by BrettMayson** [comment]
The inconsistency is gone with 1.0, a new ticket can be created if there is still something missing
