### ISSUE TITLE
Signatures failing

### ISSUE THREAD

**Issue by JasperRab** [BrettMayson/HEMTT#461]
Signatures are failing when validating with DSUtils or running a test on a dedicated server (Linux) (via -checkSignatures parameter).

A line from DSUtils:
`Key not found for signature D:\Github\etr-mods\etr_operation\.hemttout\release\addons\etr_operation_main.pbo.etr_operation_1.0.0.0.bisign`

A line from server log:
`10:39:18 Warning Message: Proper signatures not found for /home/steam/steamcmd/arma3/server_operation_private/mods/@etr operation\addons\etr_operation_main.pbo. Test FAILED!`

Meanwhile for both tests the bikey was present in the keys folder.

**Comment by BrettMayson** [comment]
Fixed in https://github.com/BrettMayson/HEMTT/releases/tag/v0.10.0-a17

Thanks for the report!
