### ISSUE TITLE
ASC incorrect input and output dir.

### ISSUE THREAD

**Issue by JasperRab** [BrettMayson/HEMTT#463]
On windows it seems possible to use relative paths on ASC.
Right now a sqfc.json look like this:
```json
{
  "inputDirs": [
    "C:\\Users\\Jaspe\\AppData\\Local\\Temp\\hemtt\\Github_etr-mods_etr_operation\\asc\\source"
  ],
  "outputDir": "C:\\Users\\Jaspe\\AppData\\Local\\Temp\\hemtt\\Github_etr-mods_etr_operation\\asc\\output",
  "includePaths": [],
  "excludeList": [],
  "workerThreads": 16
}
```

While it could look like this:
```json
{
  "inputDirs": [
    "z"
  ],
  "outputDir": "output",
  "includePaths": [],
  "excludeList": [],
  "workerThreads": 16
}
```
Where the input dir looks like this: `...\asc\z\etr_operation\addons\...`

This means that the whole path of `/Users/Jaspe/AppData/Local/Temp/hemtt/Github_etr-mods_etr_operation/asc/source/`
won't be show like it is now:
![image](https://user-images.githubusercontent.com/12704305/216765997-0a244f34-4098-45e8-a7ae-f954ca2e295e.png)
Left using the 2nd sqfc stuff, right using what hemtt comes up with.

Idk if it works the same in linux though.
But this might be able to be uses instead of changing it in ASC.

**Comment by jonpas** [comment]
ASC should be fixed either way, with or without this.

**Comment by JasperRab** [comment]
ASC seems to add the `inputDirs` bit to the final path for sqfc, which is correct because normally you give it an absolute path from P drive.
And hemtt is giving it a absolute path where the appdata path is shown, thus adding the whole path to the final path for sqfc.

I feel like hemtt is actually using it incorrectly.

Example:
The output directory has this:
`Users\Jaspe\AppData\Local\Temp\hemtt\Github_etr-mods_etr_operation\asc\source`
And in that `source` dir the addons dir is.

So this has the added absolute path of, which is configured in the json:
`C:\\Users\\Jaspe\\AppData\\Local\\Temp\\hemtt\\Github_etr-mods_etr_operation\\asc\\source`

**Comment by PabstMirror** [comment]
maybe just test if `p:\` exists and `ArmaScriptCompiler.exe` exists then just run it natively
it's also about 60x faster than doing the sqf demacroing in hemtt

**Comment by BrettMayson** [comment]
HEMTT's is also smarter and will provide more useful feedback, but I also haven't spent much time on optimizing. It's already fast enough for CI imo anyway
