### ISSUE TITLE
Allow .zip compression to be disabled

### ISSUE THREAD

**Issue by Seb105** [BrettMayson/HEMTT#481]
The zip compression is cool if your workflow needs it, however for a large mod I need to build (12gb), it is an extremely slow process taking about 5 minutes even on an SSD. This is about twice that the actual build process takes, and is frustrating as I don't need the zip for anything.

It would be good to be able to replicate the old behavior: in the releases folder, a folder with the version name is created and the copied in.

**Comment by BrettMayson** [comment]
Should be implemented as an option under `hemtt.release`, and a `--no-archive` flag

```toml
[hemtt.release]
archive = false
```

```bash
hemtt release --no-archive
```

**Comment by BrettMayson** [comment]
Implemented on main, will be released in 1.3.0
