### ISSUE TITLE
error: could not find `hemtt` in registry `crates-io` with version `*`

### ISSUE THREAD

**Issue by DarkWanderer** [BrettMayson/HEMTT#488]
Documentation states: 

> If you have [Rust](https://www.rust-lang.org/) installed, you can install HEMTT from [crates.io](https://crates.io/crates/hemtt) with cargo install hemtt.

However, when trying that, I encounter a titular error. Is this no longer (or not yet) supported?

(I am currently using the source+`cargo install --path bin` but was interested in a more automatic way)

**Comment by BrettMayson** [comment]
Ah right, I forgot that was added and would be published with the 1?3.0 release. No that is not live yet.
