### ISSUE TITLE
v1.3.0 - error: IO Error: Permission denied (os error 13)

### ISSUE THREAD

**Issue by DarkWanderer** [BrettMayson/HEMTT#489]
`/tmp` is usually shared between all users on a VM/hardware server. HEMTT creates a `/tmp/hemtt/` directory there with 755 permissions. This results in following errors for other users:
```
 INFO Config loaded for Dynamic Operations 0.2.1.1-69c2dc82
 INFO Creating `build` version
error: IO Error: Permission denied (os error 13)
```
Possible solution: ensure `/tmp/hemtt` permissions are `777` + add one more level of directory with UID (`/tmp/hemtt/12345`), to avoid possible collisions

**Comment by BrettMayson** [comment]
Implemented in 5893ff069b6582a513306c2a2cdba724c8c58ee1, it will use `/tmp/hemtt/{username}/`
