### ISSUE TITLE
v1.30: Models not being binarised

### ISSUE THREAD

**Issue by Seb105** [BrettMayson/HEMTT#490]
Not a new issue, was present in previous versions.

Logs are saying models are getting binarised.

`2023-04-16T18:21:12.827890Z  INFO ThreadId(01) Binarized 24 files`

This for sure refers to models as I have 24 models in the mod.

Reinstalling A3 tools doesn't seem to do anything.

**Comment by BrettMayson** [comment]
What project, and how are you checking the files?

What command are you using?

**Comment by Seb105** [comment]
Using hemtt release. 

I'm not sure what you mean by checking the files - they did used to get binarised with 0.7.6, so I don't _think_ there is any issue with the models. 

I will DM you the project folder.

**Comment by BrettMayson** [comment]
How do you know they are not getting binarized?

**Comment by BrettMayson** [comment]
Fixed in fc29e82191bab7b6193aec718cb4545a5312ec57 and released in v1.3.1, thanks for providing the project!
