### ISSUE TITLE
Display config.cpp snippet on prebuild error

### ISSUE THREAD

**Issue by erem2k** [BrettMayson/HEMTT#493]
I have a bunch of .hpps getting included into each other (CfgWeapons_*.hpp -> CfgWeapons.hpp -> config.cpp) and then into config.cpp in the addon.

One of them has an error, `hemtt build` returns this:

```
Clean       
Checks
Prebuild    
error: Failed to parse config `addons\cup_uniforms\config.cpp`
    error at 444:163: expected one of `class`, `[a-zA-Z0-9_]`, `}`, `delete`

error: Unable to build `addons\cup_uniforms`
```

Can the build be configured to display the snippet where the error was encountered?
From other issues seems that `hemtt dev` in earlier versions did exactly that, but since then the command has been removed; or alternatively view the preprocessed config.cpp where the error lines would match.

**Comment by BrettMayson** [comment]
Older HEMTT versions are not supported, you seem to be running a version prior to 1.0
