### ISSUE TITLE
Does not find CBA addons

### ISSUE THREAD

**Issue by diraven** [BrettMayson/HEMTT#495]
```
error: `#include` target `"\\x\\cba\\addons\\main\\script_macros_common.hpp"` was not found
```

Setup is pretty standard, prefixes are in place, CBA is also a the prefix it's supposed to be. What am I doing wrong? Any pointers?

**Comment by BrettMayson** [comment]
You need to have an include folder that has external files, you can checkout how ACE3 does it here.

https://github.com/acemod/ACE3/tree/master/include

**Comment by diraven** [comment]
Thank you, that did the trick.
