### ISSUE TITLE
Working with macroses in cpp

### ISSUE THREAD

**Issue by diraven** [BrettMayson/HEMTT#496]
Having macroses in cpp files causes errors like:
```
 19 |         function = QFUNC(someFunctionName);
    |                    ^ expected one of: [LeftBrace, DoubleQuote, Digit(0)]
help: Did you forget to place quotes around a string? Or perhaps you forgot to define / import a value.
```
Is there a way around it?

PS: Just wanted to say "Thanks". It does everything I automated with Python and more. Very convenient and immensely useful.

**Comment by BrettMayson** [comment]
Is that macro defined? Are you including the file that defines it?

**Comment by diraven** [comment]
Yes, sure. It's a CBA macro. Here is an example of a class that would fail:

```cpp
class CfgPatches
{
  class ADDON
  {
    name = COMPONENT_NAME;
    author = "...";
    url = "...";

    requiredVersion = 2.10;
    requiredAddons[] = {"CBA_main", "PY3_Pythia"};
    units[] = {};
    weapons[] = {};
  };
};
```

Error:
```
error: Expected `[LeftBrace, DoubleQuote, Digit(0)]`, found `Word("COMPONENT_NAME")`,

   --> addons/state/config.cpp:7:12
    |
  7 |     name = COMPONENT_NAME;
    |            ^ expected one of: [LeftBrace, DoubleQuote, Digit(0)]
help: Did you forget to place quotes around a string? Or perhaps you forgot to define / import a value.
```

**Comment by diraven** [comment]
script_component.hpp
```hpp
#define PREFIX JAGER
#define COMPONENT state
 
// #define DEBUG_MODE_FULL

#ifdef DEBUG_MODE_FULL
#define DISABLE_COMPILE_CACHE
#define RECOMPILE
#endif


#include "\x\cba\addons\main\script_macros_common.hpp"

```

**Comment by proudCobolWriter** [comment]
Hey! I'm having the exact same error with macroses, have you found a workaround since?

**Comment by diraven** [comment]
> Hey! I'm having the exact same error with macroses, have you found a workaround since?

Nope. That's the only place I never figured out though. So I'm just using raw code there without macroses. Good thing is it only fails in ExtEventHandlers though. I didn't encounter it anywhere else. In other places it was my own fault by providing unquoted values. E.g. FUNC() or GVAR() instead of QFUNC() and QGVAR().

**Comment by BrettMayson** [comment]
Can you provide a link to a copy of the project that is getting that error

**Comment by diraven** [comment]
Interestingly enough, it works for me now. Not sure what changed since I did not update hemtt executable.
