### ISSUE TITLE
script clears out the .hemttout/dev directory

### ISSUE THREAD

**Issue by JasperRab** [BrettMayson/HEMTT#509]
Once a script has ran using `hemtt script my_script` it clears the .hemttout/dev directory.
Happens on both 1.5.0, 1.5.1 and 1.5.2.

Script that is running is only a info print.

**Comment by BrettMayson** [comment]
I think it'll clear out all of .hemttout if I am not mistaken

**Comment by BrettMayson** [comment]
Hm

**Comment by BrettMayson** [comment]
Ah yeah I see the issue, I can fix it this weekend

**Comment by BrettMayson** [comment]
Was fixed in bb48d58d67beeb5548a2e095e96ff5ba6bd516eb
