### ISSUE TITLE
Addon can't be built without Git

### ISSUE THREAD

**Issue by rekterakathom** [BrettMayson/HEMTT#537]
Addons that don't have a fully set-up Git repository can't be built. This applies to projects created with ``hemtt new`` as well even though they have a basic git repository set-up.

Logfile when trying to build an addon created with ``hemtt new``:
```
2023-07-25T19:53:16.584523Z TRACE ThreadId(01) version: 1.7.1
2023-07-25T19:53:16.584595Z TRACE ThreadId(01) platform: windows
2023-07-25T19:53:16.585501Z TRACE ThreadId(01) checking for version macro in "addons/main/script_version.hpp"
2023-07-25T19:53:16.606825Z ERROR ThreadId(01) panicked at 'Unable to read version: Git(Error { code: -3, klass: 4, message: "revspec 'HEAD' not found" })', bin\src\context.rs:33:40
```

Edit: Problem seems to go away when the first commit gets made

**Comment by rekterakathom** [comment]
Disabling Git versioning doesn't fix the issue, it just changes the error.
``project.toml``:
```
[version]
git_hash = 0
```
Results in
- ``error: Git Error: revspec 'HEAD' not found; class=Reference (4); code=NotFound (-3)``

**Comment by BrettMayson** [comment]
Can you confirm if this still exists on HEMTT 1.8.0?

**Comment by JCalebBR** [comment]
Can confirm, error still persists on 1.8.0.

**Comment by aceacs123** [comment]
I am also experiencing this issue

**Comment by BrettMayson** [comment]
I am not able to reproduce this, when `version.git_hash = 0` is present the projects builds fine.

I have changed the error message from a panic to a handled error in 1.9.0.

If you can provide more info or a link to a project that is reproducing this issue, please reopen.
