### ISSUE TITLE
 throw error using CBA_fnc_addPerFrameHandler in external file

### ISSUE THREAD

**Issue by Canibus** [BrettMayson/HEMTT#543]
**HEMTT Version:** `1.7.2` **Project:** https://github.com/Canibus/EMP

**Description:**

hemtt build command throw: **thread '<unknown>' has overflowed its stack**

Everything works fine after removing "CBA_fnc_addPerFrameHandler" from moduleStartPosition.sqf file

**Comment by BrettMayson** [comment]
Please test with 1.8.0, that repo also do not exist

**Comment by Canibus** [comment]
Same issue.
[Repo](https://github.com/Canibus/EMPtest)
HEMTT Version: 1.8.0

**Comment by BrettMayson** [comment]
Comment out `#define ENABLE_PERFORMANCE_COUNTERS` in `script_component.hpp` and it will build

**Comment by Canibus** [comment]
> Comment out `#define ENABLE_PERFORMANCE_COUNTERS` in `script_component.hpp` and it will build

it works, ty

**Comment by BrettMayson** [comment]
Self recursion should be properly fixed in 1.9.0
