### ISSUE TITLE
Build version not available in scripts

### ISSUE THREAD

**Issue by Spartan190** [BrettMayson/HEMTT#545]
I automatically want to increase the build number (in the script_version.hpp) every time I make a new build.

As the Real filesystem is only available in the scripts but no the the hooks I want to create a script that I can call before I make a new build.

After executing the atteched script (based on the increment_minor example). I get an error:

```
2023-08-09T12:28:44.282596Z ERROR ThreadId(01) panicked at 'called `Result::unwrap()` on an `Err` value: ErrorFunctionNotFound("+ (core::option::Option<i64>, i64)", 11:12)', bin\src\modules\hook\mod.rs:150:51
```
[increment_build.rhai.txt](https://github.com/BrettMayson/HEMTT/files/12329686/increment_build.rhai.txt)

**Comment by BrettMayson** [comment]
Fixed in #557
