### ISSUE TITLE
Error if version macro includes more than major.minor

### ISSUE THREAD

**Issue by AdlerSalbei** [BrettMayson/HEMTT#551]
Hemtt errors if the VERSION macro includes more than the MAJOR.MINOR

`#define VERSION MAJOR.MINOR` <- Works
`#define VERSION MAJOR.MINOR.PATCHLVL-BUILD` <- error
`#define VERSION QUOTE(MAJOR.MINOR.PATCHLVL-BUILD)` <- error

Sample error:
```
Error: found "." but expected one of "4", "K", "F", "n", "x", "m", "W", "i", "7", "w", "h", "q", "Q", "U", "G", "3", "V", "D", "M", "r", "=", "N", "Y", "c", "_", "R", "d", "j", "f", "g", "p", "9", "e", "B", "5", "u", "H", "t", "b", "C", "8", "a", "2", "O", "L", "T", "v", "s", "Z", "o", "0", "X", "S", "I", "1", "P", "A", "E", "[", "k", "J", "y", "l", "6", "z"
   ╭─[/x/grad_trenches/addons/main/script_mod.hpp:6:28]
   │
 6 │ #define VERSION QUOTE(MAJOR.MINOR.PATCHLVL-BUILD)
   │                            ┬
   │                            ╰── property name
───╯
```

Logfile:
[latest.log](https://github.com/BrettMayson/HEMTT/files/12500624/latest.log)

**Comment by BrettMayson** [comment]
> `#define VERSION MAJOR.MINOR` <- Works

The other CBA template macros expect VERSION to be a float, this is not a bug in HEMTT

**Comment by BrettMayson** [comment]
I would need to see the repos to determine what is happening
