### ISSUE TITLE
Crash on missing inline semicolon in config

### ISSUE THREAD

**Issue by Eathox** [BrettMayson/HEMTT#569]
Example:
```
class CfgEventHandlers {
    class ADDON {init = "systemChat 'ADDON init'"};
};
```

Crashes with:
> ERROR panicked at 'called `Option::unwrap()` on a `None` value', libs\config\src\analyze\codes\ce4_missing_semicolon.rs:37:18

**Comment by BrettMayson** [comment]
Which version?

**Comment by Eathox** [comment]
Ah sorry forgot to specify, it happens on 1.9.0 RC3

**Comment by BrettMayson** [comment]
07e3d8816f8ec4e15d94eed06dd2ceac494d9002
