### ISSUE TITLE
[file] exclude ignores folders

### ISSUE THREAD

**Issue by ilbinek** [BrettMayson/HEMTT#585]
When using a project.toml like this
```
[files]
include=["mod.cpp"]
exclude=["/.vscode/"]
```

the `.vscode` directory still gets included in the packaged pbos.
I suspect this to be a bit isolated issue, as other people do not suffer from this problem.

I tried on another [project](https://github.com/PulsarNeutronStar/CVO-Auxiliary) whose author has not encountered this issue, but still persists on my system.

HEMTT version 1.9.1
Windows 11, Version 10.0.22621 Build 22621

project.toml from my project
```
name = "TBD Mortars"
author = "TBD Team"
prefix = "tbd"
mainprefix = "x"

[files]
include=["mod.cpp"]
exclude=["/.vscode/"]

[version]
major=0
minor=1
patch=0

git_hash=0

[hemtt.release]
sign   =true
archive=true

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
    "2369477168", # Advanced Developer Tools 
    "843577117", # RHSUSAF
]
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
]
```

**Comment by BrettMayson** [comment]
It works on files, not folders.

You would need
```toml
[files]
exclude=[".vscode/*"]
```
