### ISSUE TITLE
Support single-component build

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#595]
CUP is huge, building all of it with binarization takes over 7 minutes on a 5800X3D. A requirement for partial or single-component builds has presented itself.

Partial builds have been problematic in the past, relying on metadata resulted in requirement for `hemtt clean`, which is not too user friendly.

I recommend a simple option to build a single component without anything else. Do not care if other components are built or not, put it in the hands of the user. Essentially HEMTT should only build the PBO and that's it.

Throw a warning for it so users are informed the single-component build might not function if they do not also build the rest.

`hemtt build <component>` or `hemtt build --single <component>`

**Comment by BrettMayson** [comment]
This would be fairly straightforward to implement quickly, but it would result in the specified addon being the only PBO in .hemttout, as it gets cleared when the build starts. That would be the bigger refactor to add support for this

**Comment by jonpas** [comment]
If `--single` is given, skip clearing.
