### ISSUE TITLE
Math Symbols in Config properties causes "Invalid" error

### ISSUE THREAD

**Issue by CrashDome** [BrettMayson/HEMTT#602]
Is this supposed to happen? 

![image](https://github.com/BrettMayson/HEMTT/assets/110640480/695e55c6-de8e-4876-9abf-aa45a09b368e)

Only way I can seem to get around it is to disable rapify for that config.

**Comment by PabstMirror** [comment]
need to use a `QUOTE` macro around the expression
```
#define QUOTE(var1) #var1
```
```
x = QUOTE(0 * GUI_GRID...);
```

**Comment by CrashDome** [comment]
> need to use a `QUOTE` macro around the expression

Ah... that'd be the issue.

Kind of a workflow hurdle. Any chance this will change? You can Close if not.

**Comment by BrettMayson** [comment]
This will not change, this is better overall as it will prevent many simple mistakes.

Since the macros you are using have sqf commands, you can also use `__EVAL()` so they are evaluated once when the game loads.
