### ISSUE TITLE
`__FILE__` macro missing mainprefix (Version 1.11.0 RC 2)

### ISSUE THREAD

**Issue by PabstMirror** [BrettMayson/HEMTT#616]
input:
`_msg = format ["%1: Invalid params type: %2", __FILE__, _this];`
output:
`_msg = format ["%1: Invalid params type: %2", "cba\/addons/ui/flexiMenu/fnc_menu.sqf", _this];`
expected:
`"/x/cba/addons/ui/flexiMenu/fnc_menu.sqf"`

**Comment by BrettMayson** [comment]
The slashes have been fixed, but the lack of `\x\` at the start is odd, I can't reproduce. It does require the mainprefix set in `.hemtt/project.toml`

**Comment by BrettMayson** [comment]
The mystery was I fixed it a week ago and forgot
