### ISSUE TITLE
Add option to use realtive path for mission file with launch

### ISSUE THREAD

**Issue by ilbinek** [BrettMayson/HEMTT#621]
Add an option to use a relative path mission with the launch option.
This will allow to have a test mission in the git repo, allowing for easier testing between multiple developers.

Not sure if even possible from Arma side, if it doesn't require all missions to be in the documents/profile folders.

**Comment by BrettMayson** [comment]
Were you able to do this using the Arma path to the .hemtt folder?

Something like `\x\mymod\.hemtt\missions\my_mission\mission.sqm`

**Comment by ilbinek** [comment]
Tried it, but did not manage to get it working
