### ISSUE TITLE
ERROR panicked at bin\src\update.rs:62:52: byte index 1 is out of bounds of ``

### ISSUE THREAD

**Issue by Seb105** [BrettMayson/HEMTT#624]
My build script launches 2 instances of hemtt simultaneously, one will panic one will succeed. When I run the build script a second time, both will succeed.

Perhaps the daily version check crashes if 2 checks are made at the same instant.

[latest.log](https://github.com/BrettMayson/HEMTT/files/13752101/latest.log)

**Comment by BrettMayson** [comment]
> My build script launches 2 instances of hemtt simultaneously
This is not going to be supported, HEMTT uses files in the temporary directory and this will cause conflicts and issues.

What are you trying to do that you launch 2 instances

**Comment by Seb105** [comment]
I'm building 2 different versions of the same add-on with some changes, but it's not essential they're built at the same time so I'll just do it sequentially I guess.
