### ISSUE TITLE
Feature Request - Launch using build and release versions of project

### ISSUE THREAD

**Issue by DartRuffian** [BrettMayson/HEMTT#628]
The commands would run `hemtt build|release` and then launch Arma using any of the given presets defined in `.hemtt\project.toml`.

**Comment by BrettMayson** [comment]
I don't think this is easily doable without really complicating how launch works. The only real difference between `dev` and `build` is binarization, which can be enabled with `hemtt launch -b`. Additionally I don't see any value in using launch with release builds. I think this is niche enough that it's not going to be added

**Comment by DartRuffian** [comment]
I forgot this was even an issue I made, not sure what use-case I had but this can be easily worked around if it was really needed
