### ISSUE TITLE
[Bug]: Rhai script cannot copy a folder

### ISSUE THREAD

**Issue by WitchFreya** [BrettMayson/HEMTT#633]
# Description

Copying a folder using a script fails silently.

# Steps to Reproduce

1. Create a new project.
2. Create a folder called `existing_folder`.
3. Create a script `.hemtt/scripts/copy_folder.rhai` with the following:

```rust
let existing_folder = HEMTT_RFS.join("existing_folder");
print(`Source folder exists? ${existing_folder.exists()}`);
let target_folder = HEMTT_RFS.join("new_folder");
print(`Target folder exists? ${target_folder.exists()}`);
let success = existing_folder.copy(target_folder);
print(`Copy success? ${success}`);
```

4. Run `hemtt.exe script copy_folder`

## Output

![Failure Output](https://github.com/BrettMayson/HEMTT/assets/9843550/b2393cff-9233-4858-bee6-3286598080ed)

# User Details

- **Environment**: Windows 11, Build 22621.3007, Powershell version 5.1.22621.2506
- **Installation Method**: Winget
- **HEMTT Version**: 1.10.2

**Comment by BrettMayson** [comment]
The next release will throw an error with additional information
