### ISSUE TITLE
Display generic error when build fails

### ISSUE THREAD

**Issue by Timi007** [BrettMayson/HEMTT#648]
**Versions:**
HEMTT: `1.11.0`

**Description:**

When a build fails for what ever reason and the reason is not known by HEMTT, print at least a generic build error message.

In my case I have a not defined macro in the config. This does not display an error but the build failes.

Sample project containing an error: https://github.com/Timi007/hemtt-actions-test/tree/failed_build_no_error

Run build
```
$ hemtt build
 INFO Config loaded for Test 1.0.0.240205
 INFO Creating `build` version
 INFO Rapified 1 addon configs
```

Trace shows:
```
2024-02-07T13:39:32.762979Z TRACE ThreadId(01) phase: pre_build (Rapifier) (failed)
```

PBO does not exist in `.hemttout/build`.

**Expected:**
```
$ hemtt build
 INFO Config loaded for Test 1.0.0.240205
 INFO Creating `build` version
 INFO Rapified 1 addon configs
 ERROR Failed to build PBO due to unknown reason
```

**Comment by DartRuffian** [comment]
Same missing error on build. My latest.log is attached here and here is the commit in one of my projects with the changes that caused the error: https://github.com/Dart-Armory/ChatWheel-Redux/commit/b85c72ba5300775dc49e5df363ca634ce02880cf
[latest.log](https://github.com/BrettMayson/HEMTT/files/14217817/latest.log)

**Comment by BrettMayson** [comment]
Fixed, will be in the next release
