### ISSUE TITLE
`with` syntax not supported

### ISSUE THREAD

**Issue by DarkWanderer** [BrettMayson/HEMTT#657]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.11.1`
- **Operating System:** Linux

**Description:**
HEMTT throws an error when encountering [with](https://community.bistudio.com/wiki/with) statement

**Steps to reproduce:**

1. Clone [this](https://github.com/DarkWanderer/DynamicOperations) project
2. Run `hemtt build`

**Expected behavior:**
Build without errors

**Observed behavior**
```
error[SPE2]: unparseable syntax
  ┌─ addons/main/legacy/util/fn_generateUID.sqf:5:1
  │
5 │ with missionNamespace do {
  │ ^^^^ unparseable syntax
```
Error comes from [this](https://github.com/DarkWanderer/DynamicOperations/blob/ba365eceb1eec6b39d19460a07da55e33f3db1f4/addons/main/legacy/util/fn_generateUID.sqf#L5) line

**Logs:**

See https://github.com/DarkWanderer/DynamicOperations/actions/runs/8042471082/job/21963252322?pr=81#step:6:571

**Comment by PabstMirror** [comment]
missing semicolon on line 3
https://github.com/DarkWanderer/DynamicOperations/blob/ba365eceb1eec6b39d19460a07da55e33f3db1f4/addons/main/legacy/util/fn_generateUID.sqf#L3

**Comment by DarkWanderer** [comment]
Ah. My bad then, thank you for looking
