### ISSUE TITLE
Show path to warned "non-config" cpp file

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#658]
**Tools (complete and add to the following information):**
- **HEMTT:** `x.xx` 1.11.1 stable
- **Operating System:** Linux

**Description:**
```
 WARN config.old.cpp - cpp files other than config.cpp are usually not intentional. use hpp for includes
```
It would be nice if this warning would give the path to the file.

**Steps to reproduce:**

1. Have "non-config" cpp file
2. Run `hemtt build`

**Expected behavior:**
A path to warned file shown.

**Logs:**
/

**Additional context:**
/

**Comment by BrettMayson** [comment]
\>:( confused me for a bit there

> HEMTT: x.xx 1.11.1 stable

you were running main btw, this warning is unreleased

**Comment by jonpas** [comment]
Hmm, might have mixed up what I ran where. :D
