### ISSUE TITLE
Allow suppressing help and uppercase component warning

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#661]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.11.1 stable`
- **Operating System:** Any

**Description:**
Allow suppressing 2 things:
- `WARN Addon name My_Addon is not lowercase, it is highly recommended to use lowercase names`
- ~~Any `help` notices such as `SAA1` and `SAA3` in SQF (or SQF notices all-around)~~

**Steps to reproduce:**

1. Run `hemtt build` on a mod with non-lowercase component name.

**Expected behavior:**
/

**Logs:**
/

**Additional context:**
Bigger content mods would require massive changes to lowercase component names, which would also break anything that extends them. Instead it is better to just lower-case the PBO names in a `post-build` hook or other process.

**Comment by PabstMirror** [comment]
Example:
```
00 │         _value = [0, 1] select _input;
   │                  ^^^^^^^^^^^^^^^^^^^^^ using `select` where `parseNumber` is more appropriate
   try: parseNumber _input
```
if input can be false/true/0/1 it will fail because `parseNumber 1` is invalid

**Comment by BrettMayson** [comment]
This hasn't really come up again, anyone can feel free to leave a comment on this to reopen.

Currently, HEMTT just has an exception for CUP, and I am ok with that being the solution

https://github.com/BrettMayson/HEMTT/blob/987b1329ebdb238a7d546e479bdeda3326c41b70/libs/workspace/src/addons.rs#L142-L146
