### ISSUE TITLE
Cannot NOT binarize cpp files

### ISSUE THREAD

**Issue by CrashDome** [BrettMayson/HEMTT#671]
**Tools (complete and add to the following information):**
- **HEMTT:** 1.11.2 stable
- **Operating System:** Windows 11

**Description:**
Upgraded and now notice all my config.cpp files are binarized in dev build. Also main addon has SQFC files - not sure if related. Other addons in folder have config.bin but no sqfc files.. Tried the binarize.enabled = false to no avail. Cannot for the life of me get it to stop doing this.

**Steps to reproduce:**

1. Have a project with 7 addons and 1 optional
2. Run '.\hemtt dev -O' 
3. All addons including optional have config.bin files
4. only main addon has compiled sqf files

**Expected behavior:**
Neither config.bin nor sqfc files present

**Logs:**
Available at request

**Additional context:**
only have one hemtt\project.toml file and one additional addon.toml file in main addon folder. I temporarily removed the addon.toml to see if any change and noticed none.

project.toml file:
name = "XPS"
prefix = "xps"
author= "Crashdome"
reuse_private_key = false

[files]
include = ["readme.txt"]

[binarize]
enabled = false 

- did not change anything either.

**Comment by BrettMayson** [comment]
> reuse_private_key = false

This doesn't exist on HEMTT 1.*

> [binarize] 
> enabled = false

This can only go in addon.toml

If you want to to disable config.bin, that is [rapify](https://brettmayson.github.io/HEMTT/configuration/addon.html#rapify)

Although, why do you want to disable config.bin and use config.cpp. Disabling rapify will also disable HEMTT's checks of your configs

**Comment by CrashDome** [comment]
> This can only go in addon.toml
> 
> If you want to to disable config.bin, that is [rapify](https://brettmayson.github.io/HEMTT/configuration/addon.html#rapify)
> 
> Although, why do you want to disable config.bin and use config.cpp? Disabling rapify will also disable HEMTT's checks of your configs

I see my mistake. And yes, I want to disable all checks when debugging. Some checks are not valid such as "__A3_DEBUG__ is undefined" when doing conditionals (#if __A3_DEBUG__ == 1..)   At least at this point when other tools for debugging dont solve some needs I have that I can use some macros for (yes, all macros are out of cpp files - they just dont behave properly when config is rapified). For builds I dont use these macros anyway. - Optionally maybe introduce the --no-rap parameter for dev command. I would like to globally do this once in awhile and editing several addon.toml files to turn on/off is a pain.  I use dev instead of build because I have A LOT of optionals and I want them all grouped together when debugging but seperate when producing builds. Consider maybe allowing that for dev flag? - thank you.
