### ISSUE TITLE
VSCode - Conflict with Better Comments

### ISSUE THREAD

**Issue by BrettMayson** [BrettMayson/HEMTT#680]
<div type='discussions-op-text'>

<sup>Originally posted by **@DartRuffian** April 25, 2024</sup>
HEMTT's syntax highlighting seems to overwrite the changes that Better Comments makes.

Without HEMTT plugin
![image](https://github.com/BrettMayson/HEMTT/assets/59131299/a73f36e1-f8fb-4690-a2e1-e7efa53f630e)

With HEMTT plugin
![image](https://github.com/BrettMayson/HEMTT/assets/59131299/e3e079b2-84eb-4bf6-9c0c-83952f4cdba9)

Extension info
>Name: Better Comments
Id: aaron-bond.better-comments
Description: Improve your code commenting by annotating with alert, informational, TODOs, and more!
Version: 3.0.2
Publisher: Aaron Bond
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments</div>

**Comment by BrettMayson** [comment]
@DartRuffian Did this previously work with a different SQF extension?

**Comment by DartRuffian** [comment]
> @DartRuffian Did this previously work with a different SQF extension?

Huh, I never got any notification that I was mentioned here, sorry about that!
Yes, it works perfectly fine with the [SQF Language](https://marketplace.visualstudio.com/items?itemName=Armitxes.sqf) extension.

**Comment by BrettMayson** [comment]
![image](https://github.com/BrettMayson/HEMTT/assets/3946739/2340e05d-ad51-4585-b054-f764eb78304e)
This works perfectly fine for me.

The Better Comments extension will not work with languages installed after better comments was initialized, you need to reload vscode

**Comment by DartRuffian** [comment]
Huh that's a weird bug, yeah worked fine after reloading
