### ISSUE TITLE
Syntax error when attempting to use Intercept commands

### ISSUE THREAD

**Issue by JonBons** [BrettMayson/HEMTT#681]
**Tools:**
- **HEMTT:** `1.12 stable`
- **Operating System:** Windows

**Description:**
When using Intercept there is no way to signal to HEMTT any additional commands we've added resulting in a syntax error failure.
Current workaround is to do something like ``fn_InterceptCmd = compile "interceptCmd _this";``

**Steps to reproduce:**
1. Have a project that utilizes any custom command added via Intercept
2. Try to build it

**Expected behavior:**
Some method to allow custom commands created with Intercept to be specified for HEMTT to validate against.

**Logs:**
/

**Additional context:**
/

**Comment by BrettMayson** [comment]
Implemented in the linked PR
