### ISSUE TITLE
Feature Request - Command line argument to disable p-drive requirement

### ISSUE THREAD

**Issue by DartRuffian** [BrettMayson/HEMTT#700]
Currently for projects that require a PDrive, running a Github action to build the project will fail due to missing A3 materials or textures.
Something other than a CL argument might be a better solution, but that was a potential solution we thought of.

Our project is designed to require a PDrive (or A3 folder if using HEMTT), so our very hacky solution was to have a Python script to remove the `pdrive="require"` line from the HEMTT.toml when running on CI.

**Comment by BrettMayson** [comment]
What is the use case that you require a p-drive, but want to disable the requirement?

**Comment by DartRuffian** [comment]
> What is the use case that you require a p-drive, but want to disable the requirement?

GitHub action would always fail because of missing base game files

**Comment by PabstMirror** [comment]
I'm wondering if something like this would be possible
```
[hemtt.build]
pdrive = "require"

[hemtt.check]
pdrive = "ignore"
```

allowing CI to run without a p-drive (e.g. github actions)
but release builds would still require it so p3ds get built

**Comment by DartRuffian** [comment]
I forgot that hemtt check was a thing, that would make a lot more sense for CI.
