### ISSUE TITLE
Arma 3 Tools path

### ISSUE THREAD

**Issue by johnsmm** [BrettMayson/HEMTT#708]
Hi!
Im trying to set this tool up in windows docker container and i do have arma 3 tools installed (via SteamCMD) in `C:\Steam\steamapps\common\Arma 3 Tools>` but i dont have any reg key.

Is there way provide the tool where to look for arma 3 tools? or i need to make reg key? 
Cheers!

**Comment by BrettMayson** [comment]
This will be in `1.12.4` by setting `HEMTT_BINARIZE_PATH` to the folder that contains `binarize_x64.exe`
