### ISSUE TITLE
[Feature Request] Add ability to pass CLI params to hemtt executable for launch presets

### ISSUE THREAD

**Issue by DartRuffian** [BrettMayson/HEMTT#735]
Allow launch presets to specify hemtt params.

A basic use-case is adding a preset to binarize files and disable filepatching for testing animations quickly. Doing `hemtt launch -b --no-filepatching` is fine, but might be a bit annoying to remember the syntax (i.e. "Is it `-no-filepatching` or `-no-file-patching`" or something) 

Example:
```toml
[hemtt.launch.animations]
hemtt_parameters = [
    "-b",
    "--no-filepatching",
]
```

**Comment by BrettMayson** [comment]
I think just `cli` or `options` would be good, shouldn't be too confusing with context

**Comment by DartRuffian** [comment]
Theoretically it would just be passed to the executable directly, why make it so you can't use the shorthand?
Most people would probably still use the full parameter anyway for readability, but seems like extra logic that doesn't really need to be there

**Comment by BrettMayson** [comment]
It would not be passed to the executable, we're already running

**Comment by DartRuffian** [comment]
Yeah that makes sense, clearly wrote it too early in the morning. Yeah probably only allow fully spelled out parameters for readability
