### ISSUE TITLE
Book - Update github pages with the current version on main

### ISSUE THREAD

**Issue by OverlordZorn** [BrettMayson/HEMTT#742]
![grafik](https://github.com/user-attachments/assets/c2c2a8dc-003d-41a5-8254-88d6a33bda32)

**Comment by BrettMayson** [comment]
This functionality is not released, so it's not in the public book

**Comment by OverlordZorn** [comment]
huh?

**Comment by OverlordZorn** [comment]
but its mentioned already? just the codeblock example is missing?

**Comment by OverlordZorn** [comment]
Ohhhhh i see what going on. seperate launch.toml, but `extends = default` works already.
