### ISSUE TITLE
[Feature Request] Case-sensitive includes

### ISSUE THREAD

**Issue by DartRuffian** [BrettMayson/HEMTT#762]
An option to make includes be case-sensitive, primarily to match CI.

For example, trying to include a file named `cfg\cfgWeapons.hpp` with `#include Cfg\CfgWeapons.hpp` will fail, or at least give a warning. Maybe even the option to change between error, warning, or ignore.

**Comment by BrettMayson** [comment]
I think this was a regression at some point, hemtt should've been check for includes case insensitive, but Linux is complaining about it again, not completely sure though

**Comment by DartRuffian** [comment]
Interesting, I wouldn't know if it had checked in the past or not because we only setup CI for hemtt semi-recently (~3 months ago)

**Comment by BrettMayson** [comment]
Will warn on Windows, and error on Linux if the cases don't match
