### ISSUE TITLE
`check` command creates an empty folder in .hemttout

### ISSUE THREAD

**Issue by Timi007** [BrettMayson/HEMTT#765]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.13.0`
- **Operating System:** Windows

**Description:**
The `hemtt check` commands creates an empty folder named check in `.hemttout/`.

**Steps to reproduce:**

1. Run `hemtt check`

**Expected behavior:**
No empty folder should be created.

**Additional context:**
Should have been fixed in #651.

**Comment by BrettMayson** [comment]
It was removed from `value` and `check` for the PR, but `check` is a pretty feature full command, even though it does not create PBOs. The `.hemttout` folder will be created regardless if a subfolder for `check` is created. Even if that file is empty right now, it can be used by hooks, and could be used by HEMTT in the future.

I don't consider this something that needs fixing, even if right now it is not strictly required

**Comment by PabstMirror** [comment]
`.hemttout\ci_annotations.txt` is populated with lint results, I think this is desired behavior, especially if used in CI
