### ISSUE TITLE
Can't copy from HEMTT_VFS to HEMTT_OUT in pre_build hook

### ISSUE THREAD

**Issue by DerZade** [BrettMayson/HEMTT#783]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.13.0` 
- **Operating System:** Windows 11

**Description:**
[Example for `copy`](https://brettmayson.github.io/HEMTT/rhai/library/filesystem.html#copypath) does not work in `pre_build` hook:
```
let path =  HEMTT_VFS.join("docs");
if !path.exists() { throw "does not exists" }

path.copy(HEMTT_OUT.join("docs"));
```

Fails with:
```
error[BHE3]: Script /.hemtt/hooks/pre_build/02_copy_extension.rhai failed at runtime
   ┌─ .hemtt/hooks/pre_build/02_copy_extension.rhai:38:37
   │
38 │ path.copy(HEMTT_OUT.join("docs")); 
   │                                       Function not found: copy (vfs::path::VfsPath, std::path::PathBuf) (line 38, position 6)

```

**Comment by BrettMayson** [comment]
Hm, yeah there isn't a function that handles copying from the virtual file system to the real file system.

Can you post what your use case is? This might be better handled another way, or maybe you're just the first to hit this

**Comment by BrettMayson** [comment]
Feel free to reopen with more info
