### ISSUE TITLE
Incomprehensible error message when include path in SQF does not exist

### ISSUE THREAD

**Issue by Timi007** [BrettMayson/HEMTT#839]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.13.5`
- **Operating System:** Windows

**Description:**
When I have an `#include` in an SQF to a file that does not exist because the file name has a spelling mistake, I get following incomprehensible error message:
```
ERROR Failed to execute command:
Preprocessor error: Coded error
```

**Steps to reproduce:**
1. Write `#include "test.sqf"` into any SQF file (e.g. `XEH_preInit.sqf`). Make sure `test.sqf` does not exist.
2. Run `hemtt build`

Test project: https://github.com/Timi007/hemtt-actions-test

**Expected behavior:**
A clear error message similar to an include error for config:
```
error[PE12]: include not found
   ┌─ addons/main/config.cpp:31:11
   │
31 │ #include "test.sqf"
   │           ^^^^^^^^ not found
```

**Comment by BrettMayson** [comment]
This has already been fixed and a hot fix will be released soon
