### ISSUE TITLE
Config: filetype warnings - False Positives

### ISSUE THREAD

**Issue by DartRuffian** [BrettMayson/HEMTT#851]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.14.1 stable`
- **Operating System:** Windows

**Description:**
The `allow_no_extension` setting reports lots of false positives since it (seemingly) checks the property names. Below is an incomplete list of false positives. I don't think something like this could ever be 100% compatible with everything without a large amount of hard coding, but in-case it helps.
- `sounds` (in fire mode config): Array of class names to use for sounds
- `soundBegin`: Array of property names and weighted randoms
- `multiSoundHit` Same as `soundBegin`
- `soundBullet`: Sound when a bullet casing hits the ground
- `sound3DProcessingType`: Type of 3D processor to use for sound sets
- `soundShaders`: Array of sound shaders to use in a sound set
- `explosionSoundEffect`: CfgSounds(?) class name
- `nameSound`: For radio protocol, not sure if enum-like value or defined in some class somewhere

**Steps to reproduce:**

1. Enable the `allow_no_extension` setting
2. Run `hemtt check|launch|etc.`

**Expected behavior:**
HEMTT should exclude these (and similar) properties from file extension checking. More reasonably, maybe only specific named properties (e.g. `model`, `picture`, etc.) would only be checked in certain classes? Would need to only be for certain classes for other mods defining their own root classes. For example, [ACE Arsenal Extended](https://github.com/jetelain/AceArsenalExtended/tree/main?tab=readme-ov-file#sample) uses a `model` property that is a class defined elsewhere, not a file path to a `.p3d` file.

**Logs:**
N/A

**Additional context:**
N/A

**Comment by BrettMayson** [comment]
I think the biggest thing is just ignore values without any `\`, since no one should be putting files in the root of Arma's file system

**Comment by DartRuffian** [comment]
Yeah that's probably the best way to go about that
